name: Deploy on AWS workflow

on:
  # Triggers the workflow on push only for the main branch
  push:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    name: Deploy AWS Lambda
    env:
      ## Environment variable
      LAMBDA_ROLE_ARN: ${{ secrets.LAMBDA_ARN_VAR }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 11
          
      - name: Build artifact
        run: mvn clean package -DskipTests
        
      - name: Deploy AWS Lambda
        shell: sh
        run: ./target/manage.sh create
