name: Deploy on AWS workflow

on:
  # Triggers the workflow on push only for the main branch
  push:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
