name: Deploy on AWS workflow

on:
  # Triggers the workflow on push only for the main branch
  push:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    name: Deploy AWS Lambda

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 11
          
      - name: Build artifact
        run: mvn clean package -DskipTests
        
      - name: Deploy zip function to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: BirthdayAwsLambda
          zip_file: target/function.zip
          role: ${{secrets.LAMBDA_ARN_VAR}}
          runtime: java11
