name: PR Verify

on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

jobs:
  
  tests:
    
    name: Execute tests
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      # Runs Maven action
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 11
          
      - name: Integration tests
        run: mvn clean test
